### ISSUE TITLE
Doesn't fit to screen

### ISSUE THREAD

**Issue by Falling-Into-Black** [sidke/fimod#4]
Whenever I start the mod I can only view the top part to my factory and it never shows the whole thing
![screenshot 2017-04-12 at 09 35 58](https://cloud.githubusercontent.com/assets/27358676/24963175/76eda170-1f63-11e7-97e4-3e96b8b4353a.png)
That is as far as I can scroll down

**Comment by Falling-Into-Black** [comment]
Oh and also the fullscreen doesn't fix it

**Comment by fszeliga** [comment]
could you try installing ad block plus? that will get rid of advertisement and hopefully fix that issue

**Comment by Falling-Into-Black** [comment]
I just got a general free ad blocker because I have an anti virus the free one works if it gives me a virus it won't stay for long It fixes the issue.
